[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[test.validator]
url = "http://127.0.0.1:8899"

[test]
startup_wait = 10_000

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
# --resolveJsonModule ./tsconfig.json 

# [workspace]
# types = "./js/stateless.js/src/idls"
# idls = "./js/stateless.js/src/idls"

[programs.localnet]
account_compression = "7NSaKQZr5zL3LafGF48VaycvKcsBVdLZnWs3XW8cwGQA"
light_compresed_token = "8HqZ1XgE6KHceeX8AFrriJd7yu2pqWaqWAErJLnWYVHv"
light_registry = "7Z9Yuy3HkBCc2Wf3xzMGnz6qpV4n7ciwcoEMGKqhAnj1"
light_system_program = "H5sFv8VwWmjxHYS2GB4fTDsK7uTtnRT4WiixtHrET3bN"