[workspace]
resolver = "2"
members = [
    "hasher.rs/src/wasm",
    "heap",
    "circuit-lib/*",
    "macros/*",
    "merkle-tree/*",
    "programs/*",
    "test-utils",
    "utils",
    "xtask",
    "examples/token-escrow/programs/*",
    "test-programs/*",
    "forester",
    "photon-api",
    "sdk"
]

[profile.release]
overflow-checks = true

[profile.test]
opt-level = 2

[workspace.dependencies]
solana-banks-interface = "=1.18.17"
solana-program = "=1.18.17"
solana-sdk = "=1.18.17"
solana-program-test = "=1.18.17"
solana-client = "=1.18.17"
solana-cli-output = "=1.18.17"
solana-transaction-status = "=1.18.17"
spl-token = "4"
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[patch.crates-io]
"solana-account-decoder" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-accounts-db" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-banks-client" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-banks-interface" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-banks-server" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-program" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-cli-output" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-program-test" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-program-runtime" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-rpc-client" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-rpc-client-api" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-runtime" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-sdk" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-sdk-macro" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-client" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-zk-token-sdk" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-frozen-abi" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-frozen-abi-macro" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
"solana-transaction-status" = { git = "https://github.com/sergeytimoshin/agave", branch = "v1.18.17-enforce-cpi-tracking" }
