[package]
name = "example-name-service"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"
rust-version = "1.75.0" 
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "example_name_service"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
light-system-program = { path = "../../../../programs/system", version = "0.3.4", features = ["cpi"]}
account-compression = { path = "../../../../programs/account-compression", version = "0.3.5",  features = ["cpi"] }
light-hasher = { path = "../../../../merkle-tree/hasher", version = "0.1.4" }
light-verifier = { path = "../../../../circuit-lib/verifier", version = "0.1.4" }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-sdk = "1.18.11"
